version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: First
          command: node -v
      - run:
          name: Second
          command: npm -v
